<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gbk" />
<title>无标题文档</title>

<style type="text/css">
body {
	background-color: #EEF2FB;
}
</style>
<link href="/css/style.css" rel="stylesheet" type="text/css" />
</head>

<body>
<table width="100%"  height="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="17" valign="top" background="/images/mail_leftbg.gif"><img src="/images/left-top-right.gif" width="17" height="29" /></td>
    <td valign="top" background="/images/content-bg.gif">
   	  <table width="100%" height="31" border="0" cellpadding="0" cellspacing="0" class="left_topbg" id="table2">
        <tr>
          <td height="31"><div class="titlebt">菜品管理界面</div></td>
        </tr>
      </table></td>
    <td width="16" valign="top" background="/images/mail_rightbg.gif"><img src="/images/nav-right-bg.gif" width="16" height="29" /></td>
  </tr>
  <tr>
    <td valign="middle" background="/images/mail_leftbg.gif">&nbsp;</td>
    <td valign="top" bgcolor="#F7F8F9"><table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
          <td colspan="4" valign="top">&nbsp;</td>
        </tr>
        <tr>
          <td width="40%" valign="top">
          	<table width="100%"  border="0" cellpadding="0" cellspacing="0" class="line_table">
              <tr>
                <td width="7%" height="27" background="/images/news-title-bg.gif"><img src="/images/news-title-bg.gif" width="2" height="27"></td>
                <td width="93%" background="/images/news-title-bg.gif" class="left_bt2">添加</td>
              </tr>
              <tr>
                <td  colspan="2">
                <form action="/admin/doaddmenu" method="post">
             
                <table width="80%" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <td width="20%">菜名</td>
    <td width="80%"><input name="name" type="text" /></td>
  </tr>
   <tr>
    <td width="20%">分类</td>
    <td width="80%">
    <select name="menuclassify">
    <?php 
    foreach ($this->mres as $val)
    {
    ?>
    <option  value=<?php echo '"'.$val["tb_menuclassify_id"].'"'?>><?php echo $val["tb_menuclassify_name"]?></option>
   <?php 
}
   ?>
   
    </select>
    </td>
  </tr>
  
    <tr>
    <td width="20%">商家</td>
    <td width="80%">
    <select name="merchant" >
    <?php 
    foreach ($this->sres as $val)
    {
    ?>
    <option value=<?php echo '"'.$val["tb_merchant_id"].'"'?>><?php echo $val["tb_merchant_name"]?></option>
   <?php 
}
   ?>
   
    </select>
    </td>
  </tr>
   <tr>
    <td width="20%">单价</td>
    <td width="80%"><input name="price" type="text" /></td>
  </tr>
   <tr>
    <td width="20%">描述</td>
    <td width="80%"><textarea name="desc" cols="15" rows=""></textarea></td>
  </tr>

  <tr>
    <td width="20%" colspan="2" align="center"><input name="save" type="submit" value="添加" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="/admin/menumanage" target="_self">取消</a></td>
  </tr>
  
  
  
</table>
</form>

                
                
                </td>
              </tr>
            </table></td>
        </tr>
      </table></td>
    <td background="/images/mail_rightbg.gif">&nbsp;</td>
  </tr>
  <tr>
    <td valign="bottom" background="/images/mail_leftbg.gif"><img src="/images/buttom_left2.gif" width="17" height="17" /></td>
    <td background="/images/buttom_bgs.gif"><img src="/images/buttom_bgs.gif" width="17" height="17"></td>
    <td valign="bottom" background="/images/mail_rightbg.gif"><img src="/images/buttom_right2.gif" width="16" height="17" /></td>
  </tr>
</table>
</body>
</html>
