<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
<title>无标题文档</title>
<style type="text/css">
body {
	background-color: #EEF2FB;
}
</style>
</head>

<body>
<table width="100%"  height="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="17" valign="top" background="/images/mail_leftbg.gif"><img src="/images/left-top-right.gif" width="17" height="29" /></td>
    <td valign="top" background="/images/content-bg.gif">
   	  <table width="100%" height="31" border="0" cellpadding="0" cellspacing="0" class="left_topbg" id="table2">
        <tr>
          <td height="31"><div class="titlebt">餐馆管理界面</div></td>
        </tr>
      </table></td>
    <td width="16" valign="top" background="/images/mail_rightbg.gif"><img src="/images/nav-right-bg.gif" width="16" height="29" /></td>
  </tr>
  <tr>
    <td valign="middle" background="/images/mail_leftbg.gif">&nbsp;</td>
    <td valign="top" bgcolor="#F7F8F9"><table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
          <td colspan="4" valign="top">&nbsp;</td>
        </tr>
        <tr>
          <td width="40%" valign="top">
          	<table width="100%"  border="0" cellpadding="0" cellspacing="0" class="line_table">
              <tr>
                <td width="7%" height="27" background="/images/news-title-bg.gif"><img src="/images/news-title-bg.gif" width="2" height="27"></td>
                <td width="93%" background="/images/news-title-bg.gif" class="left_bt2">参观详情</td>
              </tr>
              <tr>
                <td  colspan="2">
                <table width="80%" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <td>id</td>
    <td>餐馆名</td>
    <td>地址</td>
    <td>电话</td>
   
    <td>操作</td>
  </tr>
  <?php 
  foreach ($this->res as $val)
  {
  ?>
   <tr>
    <td><?php echo $val["tb_merchant_id"]?></td>
    <td><?php echo $val["tb_merchant_name"]?></td>
    <td><?php echo $val["tb_merchant_address"]?></td>
    <td><?php echo $val["tb_merchant_telephone"]?></td>
    <td><a href="/admin/shop">查看/修改</a></td>
    
  </tr>
  <?php 
  }
  ?>
  <tr>
  <td colspan="7"><a href="/admin/shopadd">添加</a></td>
  </tr>
</table>

                
                
                </td>
              </tr>
              
            </table></td>
        </tr>
      </table></td>
    <td background="/images/mail_rightbg.gif">&nbsp;</td>
  </tr>
  <tr>
    <td valign="bottom" background="/images/mail_leftbg.gif"><img src="/images/buttom_left2.gif" width="17" height="17" /></td>
    <td background="/images/buttom_bgs.gif"><img src="/images/buttom_bgs.gif" width="17" height="17"></td>
    <td valign="bottom" background="/images/mail_rightbg.gif"><img src="/images/buttom_right2.gif" width="16" height="17" /></td>
  </tr>
</table>
</body>
</html>
