<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>

<style type="text/css">
body {
	background-color: #EEF2FB;
}
</style>
<link href="/css/style.css" rel="stylesheet" type="text/css" />
</head>

<body>
<table width="100%"  height="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="17" valign="top" background="/images/mail_leftbg.gif"><img src="/images/left-top-right.gif" width="17" height="29" /></td>
    <td valign="top" background="/images/content-bg.gif">
   	  <table width="100%" height="31" border="0" cellpadding="0" cellspacing="0" class="left_topbg" id="table2">
        <tr>
          <td height="31"><div class="titlebt">用户管理界面</div></td>
        </tr>
      </table></td>
    <td width="16" valign="top" background="/images/mail_rightbg.gif"><img src="/images/nav-right-bg.gif" width="16" height="29" /></td>
  </tr>
  <tr>
    <td valign="middle" background="/images/mail_leftbg.gif">&nbsp;</td>
    <td valign="top" bgcolor="#F7F8F9"><table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
          <td colspan="4" valign="top">&nbsp;</td>
        </tr>
        <tr>
          <td width="40%" valign="top">
          	<table width="100%"  border="0" cellpadding="0" cellspacing="0" class="line_table">
              <tr>
                <td width="7%" height="27" background="/images/news-title-bg.gif"><img src="/images/news-title-bg.gif" width="2" height="27"></td>
                <td width="93%" background="/images/news-title-bg.gif" class="left_bt2">用户详情</td>
              </tr>
              <tr>
                <td  colspan="2">
                <form action="#" method="post">
                
                
                
                
                
                
                <table width="80%" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <td width="20%">用户名</td>
    <td width="80%"><input name="username" type="text" /></td>
  </tr>
   <tr>
    <td width="20%">密码</td>
    <td width="80%"><input name="pwd" type="text" /></td>
  </tr>
   <tr>
    <td width="20%">电话</td>
    <td width="80%"><input name="telephome" type="text" /></td>
  </tr>
   <tr>
    <td width="20%">真实姓名</td>
    <td width="80%"><input name="name" type="text" /></td>
  </tr>
   <tr>
    <td width="20%">性别</td>
    <td width="80%"><table width="200">
      <tr>
        <td><label>
          <input type="radio" name="sex" value="1" id="sex_0" />
          男</label></td>
      </tr>
      <tr>
        <td><label>
          <input type="radio" name="sex" value="2" id="sex_1" />
          女</label></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td width="20%">用户等级</td>
    <td width="80%" ><input name="level" type="text" /></td>
    
  </tr>
  <tr>
    <td width="20%" colspan="2" align="center"><input name="save" type="submit" value="保存" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="/admin/usermanage" target="_self">返回</a></td>
  </tr>
  <tr style="display:none;">
    <td width="20%"></td>
    <td width="80%"> <input name="id" type="text" /></td>
  </tr>
  
  
</table>
</form>

                
                
                </td>
              </tr>
            </table></td>
        </tr>
      </table></td>
    <td background="/images/mail_rightbg.gif">&nbsp;</td>
  </tr>
  <tr>
    <td valign="bottom" background="/images/mail_leftbg.gif"><img src="/images/buttom_left2.gif" width="17" height="17" /></td>
    <td background="/images/buttom_bgs.gif"><img src="/images/buttom_bgs.gif" width="17" height="17"></td>
    <td valign="bottom" background="/images/mail_rightbg.gif"><img src="/images/buttom_right2.gif" width="16" height="17" /></td>
  </tr>
</table>
</body>
</html>
