<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gbk" />
<title>登陆</title>
<link href="/css/style.css" rel="stylesheet" type="text/css" />
</head>

<body >
<div id="container">
  <div id="head">
    <h1> <a id="logo" href="#"> <img alt="易订餐" src="/image/logo.png"/> </a> </h1>
    <ul class="top-nav">
      <li> <a href="/index/index">首页</a> </li>
      <li> <a href="/user/reg">注册</a> </li>
      <li> <a href="/user/index">登录</a> </li>
    </ul>
  </div>
  <div class="columns">
    <div class="inner_columns">
      <div class="left">
        <div id="content">
          <h1 id="page_title">登录<span>或者<a href="/user/reg">注册</a></span></h1>
          <form action="/user/dowlogin" method="post" class="account_form">
            <table>
              <tbody>
                <tr id="username-field">
                  <th><label for="username">用户名</label></th>
                  <td><input type="text" name="username" id="username" class="text" value=""/>
                    <div class="hint">请输入你的用户名</div></td>
                </tr>
                <tr id="password-field">
                  <th><label for="password">密码</label></th>
                  <td><input type="password" name="password" id="password" class="text" value=""/>
                    <br/>
                    <span class="hint"><a href="#">重置密码</a></span></td>
                </tr>
                <tr id="signin-field">
                  <th></th>
                  <td><input type="submit" id="signin" class="btn" value="登陆"/></td>
                </tr>
              </tbody>
            </table>
          </form>
        </div>
      </div>
      <div class="right">
        <div id="side">
          <h2></h2>
          <p></p>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="footer-outer">
  <div  id="footer">
    <div id="copyright"><span>&copy;&nbsp;2012 易订餐</span></div>
    <ul>
      <li><a href="#">网上订餐帮助</a></li>
      <li><a href="#">关于我们</a></li>
      <li><a href="#">企业订餐</a></li>
      <li><a href="#">易订餐bistro</a></li>
      <li><a href="#">我们在新浪微博</a></li>
    </ul>
  </div>
</div>
</div>
</body>
</html>
