<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gbk" />
<title>商家处理</title>
</head>
<body>
<div style="background-color: #EEE; color: #F00;">
已有商家
</div>
<div>
<table>
<?php
	foreach ($this->res as $value)
	{
		?>
		<tr>
		<td style="min-width:200px" >
		<?php 
		echo $value["tb_merchant_name"];
?>
</td><td>
		<a href="/menu/deletemerchant?id=<?php echo $value['tb_merchant_id']?>">删除</a>
		</td>
		</tr>
<?php 	
	}
?>
</table>

</div>
<div style="background-color: #EEE; color: #F00;">
增加商家
</div>
<form action="/menu/doaddmerchant" method="post">
<table>
<tr>
<td style="min-width: 200px">商家名:</td>
<td><input type="text" name="name"/></td>
</tr>
<tr>
<td style="min-width: 200px">商家地址:</td>
<td><input type="text" name="address"/></td>
</tr>
<tr>
<td style="min-width: 200px">商家电话:</td>
<td><input type="text" name="telephone"/></td>
</tr>
<tr>
<td colspan="2" style="text-align: center;"><input type="submit" value="添加" name="sb"/></td>
</tr>
</table>
</form>
</body>
</html>