
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gbk" />
<link href="/css/style.css" rel="stylesheet" type="text/css" />
<title>主页</title>
</head>

<body>
	<div id="container">
		<div id="head">
			<h1>
				<a id="logo" href="#"> <img alt="易订餐" src="/image/logo.png" />
				</a>
			</h1>
			<ul class="top-nav">
				<li><a href="/index/index">首页</a></li>
				<li><a href="/user/index">注册</a></li>
				<li><a href="/user/index">登录</a></li>
			</ul>
		</div>
		<div class="columns">
			<div class="inner_columns">
				<div class="left">
					<div id="content">
						<div class="title">
							<img src="/image/title.png" />
						</div>
						<div class="storelist">
							<ul>
								<li id="shop1">
									<div id="shoppic" class="store_pic">
										<img src="/image/shop/shop01.jpg" />
										<p>评价：</p>
									</div> <span class="storeName"><a href="#">简餐</a></span><br />
									<span class="storeTaste"><a>中餐</a></span>
									<div class="star r5">
										<a>&nbsp;</a>
									</div>





								</li>
								<li>
									<div id="shoppic" class="store_pic">
										<img src="/image/shop/shop01.jpg" />
										<p>评价：</p>
									</div> <span class="storeName"><a href="#">简餐</a></span><br />
									<span class="storeTaste"><a>中餐</a></span>
									<div class="star r5">
										<a>&nbsp;</a>
									</div>
								</li>
								<li>
									<div id="shoppic" class="store_pic">
										<img src="/image/shop/shop01.jpg" />
										<p>评价：</p>
									</div> <span class="storeName"><a href="#">简餐</a></span><br />
									<span class="storeTaste"><a>中餐</a></span>
									<div class="star r5">
										<a>&nbsp;</a>
									</div>
								</li>
								<li>
									<div id="shoppic" class="store_pic">
										<img src="image/shop/shop01.jpg" />
										<p>评价：</p>
									</div> <span class="storeName"><a href="#">简餐</a></span><br />
									<span class="storeTaste"><a>中餐</a></span>
									<div class="star r5">
										<a>&nbsp;</a>
									</div>
								</li>
								<li>
									<div id="shoppic" class="store_pic">
										<img src="image/shop/shop01.jpg" />
										<p>评价：</p>
									</div> <span class="storeName"><a href="#">简餐</a></span><br />
									<span class="storeTaste"><a>中餐</a></span>
									<div class="star r5">
										<a>&nbsp;</a>
									</div>
								</li>
								<li>
									<div id="shoppic" class="store_pic">
										<img src="image/shop/shop01.jpg" />
										<p>评价：</p>
									</div> <span class="storeName"><a href="#">简餐</a></span><br />
									<span class="storeTaste"><a>中餐</a></span>
									<div class="star r5">
										<a>&nbsp;</a>
									</div>
								</li>
								<li>
									<div id="shoppic" class="store_pic">
										<img src="image/shop/shop01.jpg" />
										<p>评价：</p>
									</div> <span class="storeName"><a href="#">简餐</a></span><br />
									<span class="storeTaste"><a>中餐</a></span>
									<div class="star r5">
										<a>&nbsp;</a>
									</div>
								</li>
								<li>
									<div id="shoppic" class="store_pic">
										<img src="image/shop/shop01.jpg" />
										<p>评价：</p>
									</div> <span class="storeName"><a href="#">简餐</a></span><br />
									<span class="storeTaste"><a>中餐</a></span>
									<div class="star r5">
										<a>&nbsp;</a>
									</div>
								</li>
								<li>
									<div id="shoppic" class="store_pic">
										<img src="image/shop/shop01.jpg" />
										<p>评价：</p>
									</div> <span class="storeName"><a href="#">简餐</a></span><br />
									<span class="storeTaste"><a>中餐</a></span>
									<div class="star r5">
										<a>&nbsp;</a>
									</div>
								</li>
								<li>
									<div id="shoppic" class="store_pic">
										<img src="/image/shop/shop01.jpg" />
										<p>评价：</p>
									</div> <span class="storeName"><a href="#">简餐</a></span><br />
									<span class="storeTaste"><a>中餐</a></span>
									<div class="star r5">
										<a>&nbsp;</a>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="right">
					<div id="side">
						<p>test</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="footer-outer">
		<div id="footer">
			<div id="copyright">
				<span>&copy;&nbsp;2012 易订餐</span>
			</div>
			<ul>
				<li><a href="#">网上订餐帮助</a></li>
				<li><a href="#">关于我们</a></li>
				<li><a href="#">企业订餐</a></li>
				<li><a href="#">易订餐bistro</a></li>
				<li><a href="#">我们在新浪微博</a></li>
			</ul>
		</div>
	</div>
</body>
</html>
